# Copyright 2020 Darius Neatu (neatudarius@gmail.com)

# tag-ul acesta va compila hello.c: "make" sau "make build"
# in BASH comentariile se pun cu # (practic pentru interpretorul de comenzi linia asta nu exista)
build:
	gcc hello.c -o hello

# tag-ul acesta va rula: "make run"
run:
	./hello

# tag-ul acesta va sterge fisierele create: "make clean"
clean:
	rm -f hello

.PHONY: clean
