# Copyright 2020 Darius Neatu (neatudarius@gmail.com)

# tag-ul acesta va compila main.c: "make" sau "make build"
build:
	gcc main.c -o main

# tag-ul acesta va rula: "make run"
run:
	./main

# tag-ul acesta va sterge fisierele create: "make clean"
clean:
	rm -f main

.PHONY: clean
